name: macos

on:
  push:
    branches:
      - master
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**
  pull_request:
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - name: Set Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set Xcode 12.4
      run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer

    - name: Upgrading CMake
      run: |
        brew upgrade cmake
        cmake --version

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add custom conan repo
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON -DSHARED_SFML=OFF

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Tests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest --rerun-failed --output-on-failure

    - name: Build Artifacts
      working-directory:  ${{github.workspace}}/build
      if: "env.BUILD_TYPE == 'Release'"
      shell: bash
      run: |
        cpack -G ZIP -C Release --config TTVGCPackConfig.cmake --verbose
        ls -alR

    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: tooter-*.zip
    #     path: ${{github.workspace}}/build

