name: ubuntu

on:
  push:
    branches:
      - master
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**     
  pull_request:
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v2
    - name: Install and Setup
      shell: bash
      run:  |
            sudo apt update
            sudo apt install gcc-10 g++-10
            sudo apt install libgl1-mesa-dev
            sudo apt install xorg-dev
            sudo apt install libxcb-render-util0-dev
            sudo apt install libxcb-xkb-dev
            sudo apt install libxcb-icccm4-dev
            sudo apt install libudev-dev
            sudo apt install libfreetype6-dev
            sudo apt install libxcb-image0-dev
            sudo apt install libxcb-keysyms1-dev
            sudo apt install libxcb-xinerama0-dev
            sudo apt install libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev libxcb-util-dev 

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add Bincrafters Remote
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON -DSHARED_SFML=OFF
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Tests
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest --rerun-failed --output-on-failure
        
      