name: ubuntu

on:
  push:
    branches:
      - master
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**     
  pull_request:
    paths:
      - CMakeLists.txt
      - CMake/**
      - src/**
      - tests/**

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v2
    - name: Install and Setup
      shell: bash
      run:  |
            sudo apt update
            sudo apt install gcc-10 g++-10
            sudo apt install libgl1-mesa-dev
            sudo apt install xorg-dev
            sudo apt install libxcb-render-util0-dev
            sudo apt install libxcb-xkb-dev
            sudo apt install libxcb-icccm4-dev
            sudo apt install libudev-dev
            sudo apt install libfreetype6-dev
            sudo apt install libxcb-image0-dev
            sudo apt install libxcb-keysyms1-dev
            sudo apt install libxcb-xinerama0-dev
            sudo apt install libx11-dev 
            sudo apt install libx11-xcb-dev
            sudo apt install libfontenc-dev
            sudo apt install libice-dev
            sudo apt install libsm-dev
            sudo apt install libxau-dev
            sudo apt install libxaw7-dev
            sudo apt install libxcomposite-dev
            sudo apt install libxcursor-dev
            sudo apt install libxdamage-dev
            sudo apt install libxdmcp-dev
            sudo apt install libxext-dev
            sudo apt install libxfixes-dev
            sudo apt install libxft-dev
            sudo apt install libxi-dev
            sudo apt install libxinerama-dev
            sudo apt install libxkbfile-dev
            sudo apt install libxmu-dev
            sudo apt install libxmuu-dev
            sudo apt install libxpm-dev
            sudo apt install libxrandr-dev
            sudo apt install libxrender-dev
            sudo apt install libxres-dev
            sudo apt install libxss-dev
            sudo apt install libxxf86vm-dev
            sudo apt install libxcb-randr0-dev
            sudo apt install libxcb-shape0-dev
            sudo apt install libxcb-sync-dev
            sudo apt install libxcb-xfixes0-dev
            sudo apt install libxcb-xinerama0-dev
            sudo apt install xkb-data
            sudo apt install libxcb-dri3-dev
            sudo apt install libxcb-util-dev

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Add Bincrafters Remote
      run: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UNIT_TESTS=ON -DSHARED_SFML=OFF
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Tests
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest --rerun-failed --output-on-failure
        
      